run:
	@go run cmd/runner/main.go

mig_up:
	@migrate -path migrations -database "postgres://<username>:<password>@<host>:<port>/<database_name>" -verbose up

mig_down:
	@migrate -path migrations -database "postgres://<username>:<password>@<host>:<port>/<database_name>" -verbose down