env: "local"
db_uri: "your db uri here"
redis_addr: "0.0.0.0:6379"
prometheus_addr: ":9100"
grpc:
  port: 44000
  timeout: 5s
clients:
  sso:
    address: "0.0.0.0:44044"
    timeout: 5s
    retriesCount: 3
app_secret: "your-secret-here"